### ISSUE TITLE
Can't replace VE Helixien 

### ISSUE THREAD

**Issue by antisocialian** [Garethp/replace-stuff-compatibility#2]
getting errors on game load as the mod appears to be trying to set/change things for the VE Helixien buildings and those don't have the ability to be changed(i.e. they are made of one thing and you don't get to choose the resource it's made of). I see something on the steam page about someone else having the same error, [professordad](https://steamcommunity.com/id/professordad) posted a link to their pastbin of the error: https://pastebin.com/rrynUcsS

**Comment by Garethp** [comment]
Should be fixed now. Thanks for the report
